export const CDN_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"
export const LOGO_URL = "https://cdn-icons-png.flaticon.com/128/4634/4634868.png"
export const MENU_API_URL =  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=12.9715987&lng=77.5945627&restaurantId="
export const GIT_USER_URL = "https://api.github.com/users/Gomedh"
export const GIT_URL = "https://github.com/gomedh"